CREATE TABLE users (
    id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE login_history(
    id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ip_address VARCHAR(45),
	CONSTRAINT fk_user
	    FOREIGN KEY (user_id)
		REFERENCES users (id)
		ON DELETE CASCADE		
);
